name: CI
on:
    - pull_request

jobs:
    phpinsights:
        runs-on: ubuntu-latest
        name: PHP Insights checks
        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v1
              with:
                  php-version: 7.4
            - run: composer install --prefer-dist --no-progress --no-suggest
            - run: vendor/bin/phpinsights -n --ansi --format=github-action
    laravel-tests:
        runs-on: ubuntu-latest
        name: Laravel Tests
        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v1
              with:
                  php-version: 7.4
            - run: composer install --prefer-dist --no-progress --no-suggest
            - run: php -r "file_exists('.env') || copy('.env.example', '.env');"
            - run: |
                mkdir -p database
                touch database/database.sqlite
            - name: Execute tests (Unit and Feature tests) via PHPUnit
              env:
                    DB_CONNECTION: sqlite
                    DB_DATABASE: database/database.sqlite
                    CACHE_DRIVER: array
                    SESSION_DRIVER: array
                    QUEUE_DRIVER: sync
              run: |
                    php artisan migrate
                    php artisan db:seed
                    php artisan test
