name: CI
on:
  push:
    branch:
      - develop

jobs:
    laravel-version:
        name: Laravel Version
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v1
              with:
                  php-version: 7.4
            - run: composer install --prefer-dist --no-progress --no-suggest
            - name: Cambiar numero de version
              run: php artisan version:patch
            - name: Crear commit
              uses: EndBug/add-and-commit@v7
              with:
                author_name: github_action
                author_email: fborquez@outlook.com
                message: 'Cambio de version'
                add: 'config/version.yml'
